'\" t
.\"     Title: lts.conf
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2008-11-18
.\"    Manual: File Formats and Conversions
.\"    Source: LTSP 5
.\"  Language: English
.\"
.TH "LTS\&.CONF" "5" "2008\-11\-18" "LTSP 5" "File Formats and Conversions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
lts.conf \- Main configuration file for LTSP
.SH "SYNOPSIS"
.PP
Any line beginning with a \*(Aq#\*(Aq is considered a comment\&. Options are of the format:
.sp
.nf
VARIABLE=value
.fi
.SH "DESCRIPTION"
.PP
This file gets parsed when LTSP client starts up\&. The section defined by [default] gets applied to all clients, unless there is a specification for a particular client that overrides it\&. The per\-client specs are prefixed by [<mac address>]
.PP
You may also name an arbitrary section with a name, with settings underneath that section\&. You may then inherit that section with the
\fILIKE\fR
variable\&. The Example section has an illustration of this\&.
.PP
boolean values are specified by \*(AqY,y,True,true\*(Aq for true and \*(AqN,n,False,false\*(Aq for false
.SH "LTS.CONF - GENERAL PARAMETERS"
.PP
\fICONFIGURE_FSTAB\fR
.RS 4
boolean, default
\fITrue\fR
.sp
/etc/fstab is generated by boot scripts
.RE
.PP
\fICRONTAB_01\&.\&.CRONTAB_10\fR
.RS 4
string, default
\fIunset\fR
.sp
A crontab line to add for a thin client\&.
.RE
.PP
\fIDNS_SERVER\fR
.RS 4
string, default
\fIunset\fR
.sp
A valid IP for domain name server Used to build the client\*(Aqs resolv\&.conf file\&. Not needed by default\&.
.RE
.PP
\fISEARCH_DOMAIN\fR
.RS 4
string, default
\fIunset\fR
.sp
sets a valid search domain in the clients\*(Aqs resolv\&.conf file\&. Used to build the resolv\&.conf file\&. Not needed by default\&.
.sp
Needed if
\fIDNS_SERVER\fR
is set
.RE
.PP
\fIHOSTNAME\fR
.RS 4
string, default
\fIunset\fR
.sp
This parameter sets the host name for the thin client, for situations when if no DNS is available\&. A hostname is auto\-generated if no hostname is set\&.
.RE
.PP
\fIHOSTNAME_BASE\fR
.RS 4
string, default
\fIltsp\fR
.sp
This parameter sets the base for the autogenerated host name for the thin client\&.
.RE
.PP
\fIHOSTNAME_EXTRA\fR
.RS 4
string, default
\fIip\fR
.sp
This parameter determines weather autogenerated host names are appended with information based on the ip address or mac address\&. Values are "ip" or "mac"\&.
.RE
.PP
\fINBD_SWAP\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
Set this to
\fBTrue\fR
if you want to turn on NBD swap\&.
.sp
If you enable this, you\*(Aqll need to add the line:
.sp
.if n \{\
.RS 4
.\}
.nf
                        nbdswapd: ALL: keepalive
                    
.fi
.if n \{\
.RE
.\}
.sp
to your
/etc/hosts\&.allow
file\&.
.RE
.PP
\fINBD_SWAP_PORT\fR
.RS 4
integer, default
\fI9572\fR
.sp
The port on which NBD swapping will occur\&. This is set to 9572 by default\&.
.RE
.PP
\fINBD_SWAP_SERVER\fR
.RS 4
IP address, default
\fISERVER\fR
.sp
The NBD swap server can exist on any server on the network that is capable of handling it\&. You can specify the IP address of that server\&. The default is whatever the value of
\fISERVER\fR
set to\&.
.RE
.PP
\fISERVER\fR
.RS 4
IP address, default
\fIunset\fR
.sp
This is the server that is used for the
\fIXDM_SERVER\fR,
\fITELNET_HOST\fR,
\fIXFS_SERVER\fR
and
\fISYSLOG_HOST\fR, if any of those are not specified explicitly\&. If you have one machine that is acting as the server for everything, then you can just specify the address here and omit the other server parameters\&. If this value is not set, it will be auto detected as the machine that the thin client booted from\&.
.RE
.PP
\fISYSLOG_HOST\fR
.RS 4
IP address, default
\fIunset\fR
.sp
If you want to send logging messages to a machine other than the default server, then you can specify the machine here\&. If this parameter is NOT specified, then it will use the
\fISERVER\fR
parameter described above\&.
.RE
.PP
\fIUSE_LOCAL_SWAP\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
If you have a hard drive installed in the thin client, with a valid swap partition on it, this parameter will allow the thin client to swap to the local hard drive\&.
.RE
.PP
\fITIMEZONE\fR
.RS 4
string, default
\fIunset\fR
.sp
The timezone code for the thin client to use\&.
.RE
.PP
\fITIMESERVER\fR
.RS 4
IP address, default
\fIunset\fR
.sp
The address of an NTP time server that the thin client can set it\*(Aqs time from\&. If unset, the thin client just uses the BIOS time\&.
.RE
.PP
\fISHUTDOWN_TIME\fR
.RS 4
string, format hh:mm:ss in 24 hour format, default
\fIunset\fR
.sp
Time at which thin client will automatically shut down\&.
.RE
.PP
\fILTSP_RW_DIRS\fR
.RS 4
string, default
\fIvaries by distro\fR
.sp
A list of directories mounted at boot with writeable permissions\&. The directory tree and permissions will be preserved, but no files within any directories will be copied\&.
.sp
Changing this value will override the defaults\&. you may append to the list by using the LTSP_RW_DIRS_EXTRA variable instead\&.
.RE
.PP
\fILTSP_COPY_DIRS\fR
.RS 4
string, default
\fIvaries by distro\fR
.sp
A list of directories mounted at boot with writeable permissions\&. The directory tree, files and permissions will be preserved\&.
.sp
Changing this value will override the defaults\&. you may append to the list by using the LTSP_COPY_DIRS_EXTRA variable instead\&.
.RE
.PP
\fILTSP_BINDFILES\fR
.RS 4
string, default
\fIvaries by distro\fR
.sp
A list of files mounted at boot with writeable permissions\&. The file will be copied to a writeable location and then bind\-mounted on top of the original file\&.
.sp
Changing this value will override the defaults\&. you may append to the list by using the LTSP_BINDFILES_EXTRA variable instead\&.
.RE
.PP
\fILTSP_FATCLIENT\fR
.RS 4
boolean, default
\fIunset\fR
.sp
Enable Fat Client support\&.
.RE
.PP
\fIFAT_RAM_THRESHOLD\fR
.RS 4
integer, default
\fI300\fR
.sp
Disable fat client support if less RAM is present\&.
.RE
.PP
\fINFS_HOME\fR
.RS 4
string, default
\fIunset\fR
.sp
Use NFS for mounting homedirs, instead of sshfs\&.
.RE
.PP
\fINFS_HOME_OPTIONS\fR
.RS 4
string, default
\fIunset\fR
.sp
Mount options to use with NFS_HOME\&.
.RE
.SH "LTS.CONF - LOCAL DEVICES"
.PP
\fILOCALDEV\fR
.RS 4
boolean, default
\fITrue\fR
.sp
This parameter enables local devices support, like CD\*(Aqs and USB sticks\&. Users plugging them in should see them on the desktop, after they\*(Aqve been allowed to access the FUSE subsystem on the server\&. Check your distibutions docs to see how this is done on your distribution\&.
.RE
.PP
\fILOCALDEV_DENY_CD\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
This parameter disables local device support for CD and DVD\-rom devices\&.
.RE
.PP
\fILOCALDEV_DENY_FLOPPY\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
This parameter disables local device support for floppy devices\&.
.RE
.PP
\fILOCALDEV_DENY_INTERNAL_DISKS\fR
.RS 4
boolean, default
\fITrue\fR
.sp
This parameter disables local device support for internal ATA and SCSI hard disk devices\&.
.RE
.PP
\fILOCALDEV_DENY_USB\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
This parameter disables local device support for USB devices\&.
.RE
.PP
\fILOCALDEV_DENY\fR
.RS 4
string, default
\fIunset\fR
.sp
This parameter disables local device support for devices matching certain patterns\&. Values are specified as a comma\-separated list of sysfs attributes, which can be obtained by using udevadm info (or udevinfo)\&. for example:
.sp
.if n \{\
.RS 4
.\}
.nf
                        udevadm info \-q env \-n /dev/hda
                        ID_TYPE=disk
                        ID_BUS=ata
                        
.fi
.if n \{\
.RE
.\}
.sp
should return a list of the attributes relevent to /dev/hda\&. to exclude this disk and disks like it using LOCALDEV_DENY: LOCALDEV_DENY="ID_BUS:ata+ID_TYPE:disk" would match devices that were on the ata bus that were disks\&.
.RE
.SH "LTS.CONF - SCRIPTS AND MODULES"
.PP
\fIMODULE_01\&.\&.\&.MODULE_10\fR
.RS 4
string, default
\fIunset\fR
.sp
Up to 10 kernel modules can be loaded by using these configuration entries\&. The entire command line that you would use when running insmod can be specified here\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
MODULE_01 = uart401\&.o
MODULE_02 = "sb\&.o io=0x220 irq=5 dma=1"
MODULE_03 = opl3\&.o
                    
.fi
.if n \{\
.RE
.\}
.sp
If the value of this parameter is an absolute path name, then
\fBinsmod\fR
will be used to load the module\&. Otherwise,
\fBmodprobe\fR
will be used\&.
.sp
In normal circumstances, you shouldn\*(Aqt need to specify anything here, as most hardware will be auto\-detected\&.
.RE
.PP
\fIRCFILE_01\&.\&.\&.RCFILE_10\fR
.RS 4
A custom rc file, default
\fIunset\fR
.sp
Additional RC scripts can be executed by the
\fBltsp\-client\-setup\fR
script\&. Just put the script in the
/opt/ltsp/i386/etc/init\&.d
directory, and specify the name of the script in one of these entries\&. Note that you must specify a full path, relative to the chroot\&. So, for example, if you have an RC file called
/opt/ltsp/i386/etc/init\&.d/myrcfile, you\*(Aqd specify:
.sp
.if n \{\
.RS 4
.\}
.nf
RCFILE_01=/etc/init\&.d/myrcfile
                    
.fi
.if n \{\
.RE
.\}
.sp
In your
lts\&.conf
file\&.
.RE
.SH "LTS.CONF - PRINTER PARAMETERS"
.PP
\fIPRINTER_0_DEVICE\fR
.RS 4
string, default
\fIunset\fR
.sp
The device name of the printer\&. Valid device names such as
/dev/lp0, or
/dev/usblp0
are allowed\&.
.RE
.PP
\fIPRINTER_0_PORT\fR
.RS 4
integer, default
\fI9100\fR
.sp
The TCP/IP Port number to use for the print server\&.
.RE
.PP
\fIPRINTER_0_TYPE\fR
.RS 4
string, default
\fIunset\fR
.sp
Can either be set to P (for parallel), U (for USB) or S (for serial)\&. Autodetected in most cases (except for serial)\&.
.RE
.PP
\fIPRINTER_0_WRITE_ONLY\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
Some parallel printers may need this set in order for the thin client to communicate to them properly\&. If you have problems with a parallel printer only printing part of the print job, try setting this to
\fITrue\fR\&.
.RE
.PP
\fIPRINTER_0_SPEED\fR
.RS 4
integer, default
\fI9600\fR
.sp
Should be set to the baud rate of the printer (serial printers only)\&.
.RE
.PP
\fIPRINTER_0_FLOWCTRL\fR
.RS 4
string, default
\fIunset\fR
.sp
Should be set to the flow control desired for the printer (serial printers only)\&.
.RE
.PP
\fIPRINTER_0_PARITY\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
Specifies whether parity should be enabled for the printer (serial printers only)\&.
.RE
.PP
\fIPRINTER_0_DATABITS\fR
.RS 4
integer, default
\fI8\fR
.sp
Specifies how many data bits for the printer (serial printers only)\&.
.RE
.PP
\fIPRINTER_0_OPTIONS\fR
.RS 4
string, default
\fIunset\fR
.sp
Specifies specific options for the printer (serial printers only)\&.
.RE
.PP
\fILDM_PRINTER_LIST\fR
.RS 4
string, default
\fIunset\fR
.sp
Comma separated list of printers that will be displayed for that thin client (requires patched cups, included in Debian and Ubuntu)\&.
.RE
.PP
\fILDM_PRINTER_DEFAULT\fR
.RS 4
string, default
\fIunset\fR
.sp
Default printer for the thin client\&.
.RE
.PP
\fISCANNER\fR
.RS 4
boolean, default
\fIunset\fR
.sp
This parameter enables scanners for the thin client\&.
.RE
.SH "LTS.CONF - KEYBOARD PARAMETERS"
.PP
\fICONSOLE_KEYMAP\fR
.RS 4
A valid console keymap, default
\fIen\fR
.sp
Allows you to specify a valid console keymap for TELNET_HOST sessions\&.
.RE
.PP
\fIXKBLAYOUT\fR
.RS 4
A valid xkb layout, default
\fIunset\fR
.sp
Consult the X\&.org documentation for valid settings\&.
.RE
.PP
\fIXKBMODEL\fR
.RS 4
A valid xkb model, default
\fIunset\fR
.sp
Consult the X\&.org documentation for valid settings\&.
.RE
.PP
\fIXKBVARIANT\fR
.RS 4
A valid xkb variant, default
\fIunset\fR
.sp
Consult the X\&.org documentation for valid settings\&.
.RE
.PP
\fIXKBRULES\fR
.RS 4
A valid xkb rules specifier, default
\fIunset\fR
.sp
Consult the X\&.org documentation for valid settings\&.
.RE
.PP
\fIXKBOPTIONS\fR
.RS 4
A valid xkb options specifier, default
\fIunset\fR
.sp
Consult the X\&.org documentation for valid settings\&.
.RE
.SH "LTS.CONF TOUCHSCREEN PARAMETERS"
.PP
\fIUSE_TOUCH\fR
.RS 4
Enable touchscreen
.sp
default <unset>, Enable touchscreen
.TS
tab(:);
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l
l l l l.
T{
X_TOUCH_DEVICE
T}:T{
Path to device
T}:T{
/dev/ttyS0
T}:T{
set device for touchscreen
T}
T{
X_TOUCH_DRIVER
T}:T{
Touchscreen driver
T}:T{
elographics
T}:T{
set driver for touchscreen
T}
T{
X_TOUCH_MAXX
T}:T{
integer
T}:T{
3588
T}:T{
Xmax
T}
T{
X_TOUCH_MAXY
T}:T{
integer
T}:T{
3526
T}:T{
Ymax
T}
T{
X_TOUCH_MINX
T}:T{
integer
T}:T{
433
T}:T{
Xmin
T}
T{
X_TOUCH_MINY
T}:T{
integer
T}:T{
569
T}:T{
Ymin
T}
T{
X_TOUCH_UNDELAY
T}:T{
integer
T}:T{
10
T}:T{
Untouch delay
T}
T{
X_TOUCH_RTPDELAY
T}:T{
integer
T}:T{
10
T}:T{
Repeat touch delay
T}
.TE
.sp 1
.RE
.SH "SOUND AND VOLUME CONTROL PARAMETERS"
.PP
These parameters allow you to control the volume on the thin client\&.
.PP
\fISOUND\fR
.RS 4
boolean, default
\fITrue\fR
.sp
This parameter enables sound for the thin client\&.
.RE
.PP
\fISOUND_DAEMON\fR
.RS 4
string, default
\fIpulse\fR
.sp
This parameter sets which sound daemon to use on the thin client\&. Values are esd, nasd, and pulse (default)\&.
.RE
.PP
\fIVOLUME\fR
.RS 4
integer, default
\fI90\fR
.sp
This represents an integer percentage of the volume, ranging from 0 to 100%\&.
.RE
.PP
\fIHEADPHONE_VOLUME\fR
.RS 4
integer, default
\fIunset\fR
.sp
This represents an integer percentage of the headphone volume, ranging from 0 to 100%\&.
.RE
.PP
\fIPCM_VOLUME\fR
.RS 4
integer, default
\fIunset\fR
.sp
This represents an integer percentage of the PCM volume, ranging from 0 to 100%\&.
.RE
.PP
\fICD_VOLUME\fR
.RS 4
integer, default
\fIunset\fR
.sp
This represents an integer percentage of the CD input volume, ranging from 0 to 100%\&.
.RE
.PP
\fIFRONT_VOLUME\fR
.RS 4
integer, default
\fIunset\fR
.sp
This represents an integer percentage of the front speaker volume, ranging from 0 to 100%\&.
.RE
.PP
\fIMIC_VOLUME\fR
.RS 4
integer, default
\fIunset\fR
.sp
This represents an integer percentage of the microphone input volume, ranging from 0 to 100%\&.
.RE
.SH "LTS.CONF - XORG PARAMETERS"
.PP
These parameters affect how Xorg behaves\&.
.PP
\fIUSE_XFS\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
Instructs the thin client to look at the
\fIXFS_SERVER\fR
option, and use XFS for serving fonts\&.
.RE
.PP
\fIXFS_SERVER\fR
.RS 4
IP address, default
\fIunset\fR
.sp
If you are using an X Font Server to serve fonts, then you can use this entry to specify the IP address of the host that is acting as the font server\&. If this is not specified, it will use the default server, which is specified with the
\fISERVER\fR
entry described above\&.
.RE
.PP
\fICONFIGURE_X\fR
.RS 4
If you want to be able to configure the individual settings of the X configuration file, without having the X automatically configure the graphics card for you, you must enable this option\&. By default this option is turned off\&. To turn it on do:
.sp
.if n \{\
.RS 4
.\}
.nf
CONFIGURE_X = True
.fi
.if n \{\
.RE
.\}
.sp
\&. You don\*(Aqt need this option just for keyboard and mouse settings\&. It corresponds to the graphic card and monitor options only\&.
.RE
.PP
\fIX_CONF\fR
.RS 4
string, default
\fIunset\fR
.sp
If you want to create your own complete X\&.org config file, you can do so and place it in the
/opt/ltsp/<arch>/etc/X11
directory\&. Then, whatever you decide to call it needs to be entered as a value for this configuration variable\&. For example: X_CONF = /etc/X11/my\-custom\-xorg\&.conf Note that for the thin client, you reference it from
/etc/X11\&.
.RE
.PP
\fIX_RAMPERC\fR
.RS 4
default \*(Aq100\*(Aq, Percentage of RAM for X server
.sp
Some programs allocate a large amount of ram in the X\&.org server running on your thin client\&. Programs like
\fBFirefox\fR
and
\fBEvince\fR
can use up so much ram, that they eventually exhaust all your physical ram, and NBD swap, causing your thin client to crash\&. If you find your clients being booted back to a login prompt, or freezing up when viewing certain PDF\*(Aqs or web pages, this may be the problem\&.
.sp
The
\fIX_RAMPERC\fR
variable stands for X RAM PERCent, and is a number between 0 and 100 that specifies how much of the free space on your thin client X\&.org is allowed to consume\&. You\*(Aqll generally want to set it at something lower than 100 percent, if you\*(Aqre having problems\&. Experimentation has shown a value between 80 and 90 will usually keep the terminal alive\&. What will then happen is the program consuming the memory will die, as opposed to the thin client itself\&. If you\*(Aqre having unexplained terminal problems, specifying:
.sp
X_RAMPERC = 80
.sp
in your
lts\&.conf
file may improve things\&.
.RE
.PP
\fIX_VIRTUAL\fR
.RS 4
string, default
\fIunset\fR
.sp
If you want to have a virtual screen which is larger than the physical screen on your thin client, you would configure that by providing a string of the form "width height" in this parameter, similar to the
xorg\&.conf
format\&.
.RE
.PP
\fIXDM_SERVER\fR
.RS 4
IP address, default
\fIunset\fR
.sp
If you\*(Aqre using the older
\fBstartx\fR
screen script, and need to specify a different XDMCP server, then you can specify the server here\&. If this parameter is NOT specified, then it will use the
\fISERVER\fR
parameter described above\&.
.RE
.PP
\fIXSERVER\fR
.RS 4
You can use this parameter to override which X server the thin client will run\&. For PCI and AGP video cards, this parameter should not be required\&. The thin client should normally be able to auto\-detect the card\&.
.sp
If, for some reason you do need to manually set it, here are some valid values:
.sp
ark, ati, atimisc, chips, cirrus_alpine cirrus, cirrus_laguna, cyrix, dummy, fbdev fglrx, glint, i128, i740, i810, imstt, mga, neomagic, newport, nsc, nv, r128, radeon, rendition, riva128, s3, s3virge, savage, siliconmotion, sis, sisusb, tdfx, tga, trident, tseng, v4l, vesa, vga, via, vmware, voodoo
.RE
.PP
\fIX_MOUSE_DEVICE\fR
.RS 4
string, default
\fIunset\fR
.sp
This is the device node that the mouse is connected to\&. If it is a serial mouse, this would be a serial port, such as
/dev/ttyS0
or
/dev/ttyS1\&. This is not needed for PS/2 or USB mice, as they are auto\-detected\&.
.RE
.PP
\fIX_MOUSE_PROTOCOL\fR
.RS 4
Should be auto\-detected\&. However, valid entries include:
.sp
sunkbd, lkkbd, vsxxxaa, spaceorb, spaceball, magellan, warrior, stinger, mousesystems, sunmouse, microsoft, mshack, mouseman, intellimouse, mmwheel, iforce, h3600ts, stowawaykbd, ps2serkbd, twiddler, twiddlerjoy
.RE
.PP
\fIX_MOUSE_EMULATE3BTN\fR
.RS 4
boolean, default
\fIunset\fR
.sp
Normally unset, may need to be set to
\fIY\fR
for certain 2 button mice\&.
.RE
.PP
\fIX_NUMLOCK\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
If this variable is set to
\fITrue\fR, then the numlock key will be defaulted to on when the terminal boots\&. Note that the
\fBnumlockx\fR
command must be installed in the chroot for this to work\&.
.RE
.PP
\fIX_COLOR_DEPTH\fR
.RS 4
Integer: 2, 4, 8, 16, 24, 32 default
\fI24\fR
.sp
This is the number of bits to use for the colour depth\&. Possible values are
\fB8\fR,
\fB16\fR,
\fB24\fR
and
\fB32\fR\&. 8 bits will give 256 colours, 16 will give 65536 colours, 24 will give 16 million colours and 32 bits will give 4\&.2 billion colours! Not all X servers support all of these values\&. The default value for this is
\fB24\fR\&.
.RE
.PP
\fIX_HORZSYNC\fR
.RS 4
min\-max values
.sp
This sets the X\&.org
\fBHorizSync\fR
configuration parameter\&. This should be auto\-detected for your monitor, however, if you want to force a lower resolution, use this parameter to do so\&.
.RE
.PP
\fIX_VERTREFRESH\fR
.RS 4
min\-max values
.sp
This sets the X\&.org
\fBVertRefresh\fR
configuration parameter\&. This should be auto\-detected for your monitor\&. If you need to force a lower resolution, use this parameter to do so\&.
.RE
.PP
\fIX_VIDEO_RAM\fR
.RS 4
string, default
\fIunset\fR
.sp
This sets the X\&.org
\fBVideoRam\fR
configuration parameter\&. The setting is in kilobytes\&. This should be auto\-detected for your monitor\&. If you need to force a different video ram setting, use this parameter to do so\&.
.RE
.PP
\fIX_OPTION_01\&.\&.\&.X_OPTION_12\fR
.RS 4
A valid Device option
.sp
This allows you to specify
\fBOption\fR
settings in the
xorg\&.conf
file, to add options to the video driver\&. A common use for this will be to test turning off acceleration in your driver, if you\*(Aqre having trouble\&. An example usage would be:
.sp
.if n \{\
.RS 4
.\}
.nf
X_OPTION_01 = "\e"NoAccel\e"" X_OPTION_02 = "\e"AnotherOption\e" \e"True\e""
                    
.fi
.if n \{\
.RE
.\}
.sp
You probably won\*(Aqt need these except in special circumstances\&.
.RE
.PP
\fIX_MONITOR_OPTION_01\&.\&.\&.X_MONITOR_OPTION_10\fR
.RS 4
string, default
\fIunset\fR
.sp
A valid Monitor option, that would normally be used in an xorg\&.conf file\&.
.RE
.PP
\fIX_MODE_0\fR, \fIX_MODE_1\fR, and \fIX_MODE_2\fR
.RS 4
string, default
\fIunset\fR
.sp
These set the X\&.org
\fIModeLine\fR
configuration\&. For example, if your thin client comes up in a higher resolution than what you want, say, 1280x1024, specifying:
.sp
.if n \{\
.RS 4
.\}
.nf
X_MODE_0 = 1024x768
                    
.fi
.if n \{\
.RE
.\}
.sp
should get your desired resolution on startup\&.
.sp
X_MODE_* require XRANDR_DISABLE=True to work\&. For drivers that support XRANDR, the XRANDR_MODE_* variabled are preferred\&. See the XRANDR section\&.
.RE
.PP
\fIX_BLANKING\fR
.RS 4
A positive integer
.sp
When set,
\fIX_BLANKING\fR
will cause DPMS standby to activate after the number of seconds provided\&. If the monitor does not support DPMS, then the blanking screensaver will activate\&. If
\fIX_BLANKING\fR
is set to 0, the monitor will remain on indefinitely\&. NOTE: This does not apply to the
\fBxdmcp\fR
or
\fBstartx\fR
screen script\&. Also, server\-side Xclients such as power managers and screensavers may override this setting\&.
.RE
.SH "LTS.CONF OPTIONS - XRANDR OPTIONS"
.PP
\fIXRANDR_DISABLE\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
Disables XRANDR output handling so that the older
\fIX_MODE_0\fR
way of setting resolution works\&. This is useful on older Xorg drivers that don\*(Aqt support XRANDR\&.
.RE
.PP
\fIXRANDR_OUTPUT_0 \&.\&.\&. XRANDR_OUTPUT_8\fR
.RS 4
string, default
\fIunset\fR
.sp
Define xrandr output \- can also be used for multihead positioning
.RE
.PP
\fIXRANDR_MODE_0 \&.\&.\&. XRANDR_MODE_8\fR
.RS 4
string, default
\fIunset\fR
.sp
Valid video mode resolution\&. Sets mode for corresponding output\&.
.RE
.PP
\fIXRANDR_NEWMODE_0 \&.\&.\&. XRANDR_NEWMODE_8\fR
.RS 4
string, default
\fIunset\fR
.sp
Specifies a valid modeline for a corresponding output\&.
.RE
.PP
\fIXRANDR_RATE_0 \&.\&.\&. XRANDR_RATE_8\fR
.RS 4
string, default
\fIunset\fR
.sp
Sets refresh rate for the corresponding output\&.
.RE
.PP
\fIXRANDR_DPI_0 \&.\&.\&. XRANDR_DPI_8\fR
.RS 4
string, default
\fIunset\fR
.sp
Sets the DPI for the corresponding output\&.
.RE
.PP
\fIXRANDR_ROTATE_0 \&.\&.\&. XRANDR_ROTATE_8\fR
.RS 4
string, default
\fIunset\fR
.sp
Sets the rotation for the corresponding output\&.
.RE
.PP
\fIXRANDR_REFLECT_0 \&.\&.\&. XRANDR_REFLECT_8\fR
.RS 4
string, default
\fIunset\fR
.sp
Sets the reflection for the corresponding output\&.
.RE
.PP
\fIXRANDR_SIZE_0 \&.\&.\&. XRANDR_SIZE_8\fR
.RS 4
string, default
\fIunset\fR
.sp
Sets the resolution for the corresponding output (for xrandr <1\&.2)\&.
.RE
.PP
\fIXRANDR_ORIENTATION_0 \&.\&.\&. XRANDR_ORIENTATION_8\fR
.RS 4
string, default
\fIunset\fR
.sp
Sets the orientation for the corresponding output (for xrandr <1\&.2)\&.
.RE
.SH "LTS.CONF OPTIONS - SCREEN SCRIPTS"
.PP
\fISCREEN_01\&.\&.\&.SCREEN_12\fR
.RS 4
string, default
\fIldm\fR
.sp
Up to 12 screen scripts can be specified for a thin client\&. This will give you up to 12 sessions on the thin client, each accessible by pressing the Ctrl\-Alt\-F1 through Ctrl\-Alt\-F12 keys\&.
.sp
Currently, possible values include: kiosk, ldm, menu, rdesktop (deprecated), shell, ssh, startx (deprecated), telnet, xdmcp, xfreerdp, xterm
.sp
Look in the
$CHROOT/usr/share/ltsp/screen\&.d
directory for more scripts, or write your own, and put them there\&.
.RE
.PP
\fITELNET_HOST\fR
.RS 4
IP address, default
\fIunset\fR
.sp
If the thin client is setup to have a character based interface, then the value of this parameter will be used as the host to telnet into\&. If this value is NOT set, then it will use the value of
\fISERVER\fR
above\&.
.RE
.SH "LTS.CONF OPTIONS - LDM OPTIONS"
.PP
\fILDM_AUTOLOGIN\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
This option allows the thin client to login automatically without the need for a username and password\&. To set it set
.sp
.if n \{\
.RS 4
.\}
.nf
LDM_AUTOLOGIN = True
.fi
.if n \{\
.RE
.\}
.sp
for the corresponding thin client\&. This will attempt to log in the thin client with username = hostname and password = hostname\&. You can also set a user and password with
\fILDM_USERNAME\fR
and
\fILDM_PASSWORD\fR
variables\&.
.RE
.PP
\fILDM_DEBUG\fR
.RS 4
boolean, default
\fIunset\fR
.sp
Turns on ldm debugging on the thin client\&. Log is written to /var/log/ldm\&.log on the thin client itself\&.
.RE
.PP
\fILDM_DIRECTX\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
This is arguably the most important LDM option, as it allows you to turn off the encrypted X tunnel via SSH, and instead run a less secure, but much faster unencrypted tunnel\&. Users who have slower thin clients will want to set this to
\fITrue\fR\&. It is set to
\fITrue\fR
by default in Fedora\&.
.RE
.PP
\fILDM_GUESTLOGIN\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
This option places a GUEST LOGIN button underneath the entry field for username and password\&. To set it set
.sp
.if n \{\
.RS 4
.\}
.nf
LDM_GUESTLOGIN = True
.fi
.if n \{\
.RE
.\}
.sp
for the corresponding thin client\&. You can also set a user and password with
.sp
.if n \{\
.RS 4
.\}
.nf
LDM_USERNAME = John
.fi
.if n \{\
.RE
.\}
.sp
and
.sp
.if n \{\
.RS 4
.\}
.nf
LDM_PASSWORD = secret
.fi
.if n \{\
.RE
.\}
.sp
, although not setting these will default to the hostname of the thin client\&.
.RE
.PP
\fILDM_GUEST_SERVER\fR
.RS 4
string, default
\fIunset\fR
.sp
This is a space\-separated list of available servers where guest logins are available\&. The first server in the list will be the default guest login server unless the user selects another from the preferences menu at login time\&.
.RE
.PP
\fILDM_ALLOW_USER\fR
.RS 4
string
.sp
This option allows you to give access to certain thin clients based on the username set in
/etc/passwd\&. For example, thin client A should only be used by Jane, Bob, and Fred, while thin client B is to be used by Harry only\&. By adding these options to the corresponding mac addresses you allow or deny access to the thin clients in question\&. Example:
.sp
.if n \{\
.RS 4
.\}
.nf
[thin:client:A:mac:address]
LDM_ALLOW_USER = Jane,Bob,Fred
[thin:client:B:mac:adddress]
LDM_ALLOW_USER = Harry
                   
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fILDM_LOGIN_TIMEOUT\fR
.RS 4
integer
.sp
This lets LDM automatically login after the set amount of time in seconds\&. If you specify this option, then do not specify LDM_AUTOLOGIN\&. Use it in this format:
.sp
.if n \{\
.RS 4
.\}
.nf
[thin:client:mac:address]
LDM_LOGIN_TIMEOUT = 25
                    
.fi
.if n \{\
.RE
.\}
.sp
Note that you will need to also set LDM_GUESTLOGIN=True for LDM_LOGIN_TIMEOUT to be useful\&.
.RE
.PP
\fILDM_USERNAME\fR
.RS 4
string, default
\fIunset\fR
.sp
This is the username that LDM will use for autologin\&.
.RE
.PP
\fILDM_PASSWORD\fR
.RS 4
string, default
\fIunset\fR
.sp
This is the password that LDM will use for autologin\&.
.RE
.PP
\fILDM_SYSLOG\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
Normally, LDM logs to a simple file on the thin client, namely
/var/log/ldm\&.log\&. This has the advantage of being fast, but the disadvantage of being hard to read for the administrator in the event of a problem, as the administrator must either spawn a shell screen session, or enable root login in tty1\&. By setting this option to "True", you can log up to the server
\fIif you\*(Aqve enabled your server\*(Aqs syslog for remote logging\&.\fR
.RE
.PP
\fILDM_SERVER\fR
.RS 4
string, default
\fIunset\fR
.sp
This is a space\-separated list of available servers for LDM to log into\&. The first server in the list will be the default server unless the user selects another from the preferences menu at login time\&.
.RE
.PP
\fILDM_LANGUAGE\fR
.RS 4
string, default
\fIunset\fR
.sp
This allows the system administrator to override the default locale settings on the server by setting the environment variables LANG, LANGUAGE and LC_ALL at login\&.
.sp
Use the LANG variable to set the default locale for LDM\*(Aqs user interface\&.
.RE
.PP
\fILDM_SSHOPTIONS\fR
.RS 4
string
.sp
Allows you to specify custom options to the ssh sessions started between LDM and the server\&.
.RE
.PP
\fINETWORK_COMPRESSION\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
Enables compression of the SSH traffic over the network\&. Note that while this will reduce your network traffic, it will increase your cpu load\&.
.RE
.PP
\fISSH_OVERRIDE_PORT\fR
.RS 4
integer, default
\fIunset\fR
.sp
If you run your ssh server different from the defult, you may set the port the thin client will use with this parameter\&.
.RE
.PP
\fISSH_FOLLOW_SYMLINKS\fR
.RS 4
boolean, default
\fITrue\fR
.sp
Causes
sshfs
mounted filesystems for local applications to follow symlinks\&. Should not need to be modified under normal circumstances\&.
.RE
.PP
\fILDM_SESSION\fR
.RS 4
string, default
\fIunset\fR
.sp
Used to chose the default session on the server\&.
.RE
.PP
\fILDM_XSESSION\fR
.RS 4
string, default
\fIXsession\fR
.sp
Allows you to specify custom script on the server for LDM to run, rather than the server\*(Aqs standard script for starting an X session (usually
\fBXsession\fR)\&.
.RE
.PP
\fILDM_LIMIT_ONE_SESSION\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
Only allow a given user to log into one thin\-client at a time\&.
.RE
.PP
\fILDM_LIMIT_ONE_SESSION_PROMPT\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
Prompt to kill processes of other logins when other logins are detected\&. Requires LDM_LIMIT_ONE_SESSION to be set\&.
.RE
.PP
\fILDM_THEME\fR
.RS 4
string, default
\fIunset\fR
.sp
Specify the name of the LDM theme\&. It can reference a directory in /usr/share/ldm/themes, or be specified as a full path to the theme dir (both relative to the chroot)\&.
.sp
To use the theme in
/opt/ltsp/i386/usr/share/ldm/themes/MYTHEME, you\*(Aqd specify:
.sp
.if n \{\
.RS 4
.\}
.nf
LDM_THEME=MYTHEME
                    
.fi
.if n \{\
.RE
.\}
.sp
In your
lts\&.conf
file\&.
.sp
Alternately, To use the theme in
/opt/ltsp/i386/etc/MYTHEME, you\*(Aqd specify:
.sp
.if n \{\
.RS 4
.\}
.nf
LDM_THEME=/etc/MYTHEME
                    
.fi
.if n \{\
.RE
.\}
.sp
In your
lts\&.conf
file\&.
.RE
.SH "LOCAL APPLICATIONS"
.PP
\fILOCAL_APPS\fR
.RS 4
boolean, default
\fITrue\fR
.sp
Enables support for running local apps on the thin client\&.
.RE
.PP
\fILOCAL_APPS_EXTRAMOUNTS\fR
.RS 4
string, default
\fIunset\fR
.sp
This parameter enables extra mount points to be mounted on the thin client with sshfs\&. This require a commas separated list of directory\&.
.RE
.PP
\fILOCAL_APPS_MENU\fR
.RS 4
boolean, default
\fIFalse\fR
.sp
Enables overriding of menu items from remote (server) applications\&. If this is set to
\fITrue\fR, local applications in the users menu will be used instead of the applications on the server\&.
.RE
.PP
\fILOCAL_APPS_MENU_ITEMS\fR
.RS 4
string, default
\fIunset\fR
.sp
This item should contain a comma separated list of application names as they appear on their \&.desktop files\&.
.RE
.PP
\fILOCAL_APPS_WHITELIST\fR
.RS 4
string, default
\fIunset\fR
.sp
Used to allow only specified space\-separated commands to be run as local apps, allow all is default if unset\&. Full\-paths are required for each command\&. No spaces in the names are allowed\&.
.RE
.SH "SAMPLES"
.SS "K12LTSP"
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
# Global defaults for all clients
# if you refer to the local server, just use the
# "server" keyword as value
# see lts_parameters\&.txt for valid values
################
[default]
    #X_COLOR_DEPTH=16
    LOCALDEV=True
    SOUND=True
    NBD_SWAP=True
    SYSLOG_HOST=server
    #XKBLAYOUT=de
    SCREEN_02=shell
    SCREEN_03=shell
    SCREEN_04=shell
    SCREEN_05=shell
    SCREEN_06=shell
    SCREEN_07=ldm
    # LDM_DIRECTX=True allows greater scalability and performance
    # Turn this off if you want greater security instead\&.
    LDM_DIRECTX=True
    # LDM_SYSLOG=True writes to server\*(Aqs syslog
    LDM_SYSLOG=True


################
# A setting stanza for an old machine
################
[oldmachine]
    X_COLOR_DEPTH=8
    X_MODE_0=800x600

################
# Example of the LIKE variable
################
[01:23:DE:AD:BE:EF]
    LIKE=oldmachine
    SCREEN_02=shell

################
#[MAC ADDRESS]: Per thin client settings
################
[00:11:25:84:CE:BA]
    XSERVER = vesa
    X_MOUSE_DEVICE=/dev/ttyS0
    X_MOUSE_PROTOCOL=intellimouse

###############
# A Thin Client Print server
# (switch off X by pointing tty7 to shell,
# to save ressources)
###############
[00:11:25:93:CF:00]
    PRINTER_0_DEVICE=/dev/usblp0
    SCREEN_07=shell

###############
# A workstation that executes a specific
# command after login
###############
[00:11:25:93:CF:02]
    LDM_SESSION=/usr/bin/myloginscript
                
.fi
.if n \{\
.RE
.\}
.sp
.SH "NOTES"
.PP
Notes about lts\&.conf that don\*(Aqt fit anywhere else go here\&.\&.\&.
.SH "SEE ALSO"
.PP
Other manpage references go here\&.\&.\&.
